# Generated by Django 3.1.5 on 2021-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(blank=True, max_length=300, verbose_name='imprint'),
        ),
    ]
