# Generated by Django 3.1.5 on 2021-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bookinstance_imprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='imprint'),
        ),
    ]
